language: objective-c
osx_image: xcode8.2
script:
- xcodebuild test -project Dratini.xcodeproj -scheme Dratini -sdk iphonesimulator -destination 'platform=iOS Simulator,id=1FD54EA7-5A25-4D6F-8599-D6F7687DA4EE,OS=10.2'


